import { Memory, Place } from '../types';

export const INITIAL_MEMORIES: Memory[] = [
  {
    id: 'mem-1',
    title: 'Golden Afternoon in Gion',
    city: 'Kyoto',
    country: 'Japan',
    date: '2023-10-14',
    formattedDate: 'Oct 14, 2023',
    story: "The way the light hit the old wooden houses was unlike anything I'd ever seen. We sat on that small bench for nearly an hour, just watching the world slow down as the sun dipped behind the shrines. The smell of roasted tea was everywhere...",
    notes: 'Bought a small ceramic cup from a local craftsman.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuASSQFMCz1Mgew4lG95gSWq43QDGYrbf2ZfQPfp1AnyS3LnN0CQmyV71ZPwEN9ZYfix2dGEGLffgGa6Z2JSp8q6sGLgwBKLYQRKxflNtXMWIlijiY76-XZ75WV9aQjBO_jiEAjfLbzUhpmP1lED0mdpXN87KWpZRHQrUAChK14lQOa1srvgba2iCrp0yRoa696haLSdq8ZQ7biKQPsJAApOsBW21eyvM0wDJMNTqrBzI7wDGkpq3MvT12PfKnXFyzl8R3nKYJFjrtRj',
    weather: 'Golden',
    moods: ['Peaceful', 'Grateful', 'Inspired'],
    category: 'Travel',
    companion: 'Partner',
    isFavorite: true,
    coordinates: { lat: 35.0037, lng: 135.7772, xPercent: 82, yPercent: 42 },
  },
  {
    id: 'mem-2',
    title: 'Reflections at the Louvre',
    city: 'Paris',
    country: 'France',
    date: '2024-05-14',
    formattedDate: 'May 14, 2024',
    story: 'The glass pyramids shimmered like diamonds under the evening sky. As dusk settled, the reflection in the shallow water basins created a symmetrical mirror of historical grandness and modern elegance.',
    notes: 'Walked along the Seine until midnight.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDtrSyeQM82yxFP4aW7KUGHKn8h9ujlcbi0ltsHQb4NRRx9TahbDCd8L-0DbWtQK_vXStXBg-CcZxevXwqwGgahbwDpNC8FZvMW9T5NEDU6afu1yqcaYJlQEDo1Iy2prNCwFGhQvfIfXJkxVNYcdoGcKu5LfbOp6gpVBwDffQ0D4ywRd73aXwZ4nEw4gO6e5sTq5Dm_KMZDrlicHK3MJJdv_eWeevxqPBwJ3yMvcdL_zM-y7RruYVQu9hCjXCiLTbRxn8MgvnL7dQqh',
    weather: 'Golden',
    moods: ['Inspired', 'Loved'],
    category: 'Travel',
    companion: 'Partner',
    isFavorite: true,
    coordinates: { lat: 48.8606, lng: 2.3376, xPercent: 49, yPercent: 32 },
  },
  {
    id: 'mem-3',
    title: 'Slow Mornings',
    city: 'Amalfi Coast',
    country: 'Italy',
    date: '2024-06-02',
    formattedDate: 'June 2, 2024',
    story: 'Finding peace in the simple ritual of coffee and quiet conversations on the cliffside balcony. The sea below stretched endlessly into the warm horizon.',
    notes: 'Fresh espresso, citrus jam, and warm breeze.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA6kpy2fbf-PaG9hB56Z8O-1W8YrSsIVReTCuy-VBInfKjmTn7mtm7JRI1hL_0lCex0ccLbOe2sZj2wrNvju5Uh60HQPBfB_P4S_a-bC9haIyVaTYHfTeE50yMx3n8BW6KTTwRii1WzlcXqq7NohCqzSCke8wtpupB3F3nvaVYTxW4DZxpUGWk4Ar6HxxVnkQ0QlfwX7ZKyEEov57Ly2AMj4YaBDBD5E5VZTBj8hhuPle1iL7HyayEoxsTdNVhagWBMiMFdSgJPD7yY',
    weather: 'Sunny',
    moods: ['Relaxed', 'Peaceful'],
    category: 'Coffee',
    companion: 'Myself',
    isFavorite: false,
    coordinates: { lat: 40.634, lng: 14.6027, xPercent: 52, yPercent: 36 },
  },
  {
    id: 'mem-4',
    title: 'City Lights',
    city: 'London',
    country: 'United Kingdom',
    date: '2023-09-20',
    formattedDate: 'Sep 2023',
    story: 'The rain turned the cobblestone streets into a mirror of neon and history. Red double-decker buses glided past traditional brick pub fronts as laughter spilled into the cool night.',
    notes: 'Sheltered under a canvas canopy drinking Earl Grey.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBObeK0pxiKnCciZ9akYrkEdyAY9gixku5u73bYRWPR-CDuvn9x1X9FYhyrlZvnMMoDMD-kAOnTB5HmLbhaHShHnAm_my_RAQT76gn3zCy5TYRKBYN7LBC8NJz017p84blcTAOyPAkuYi9jhkyFxOAnIxxJ4oamJZxlvrOaiImDW_-mLWYMo0jAJDxH6WDHT2NpVdQ2sj6iAfyNC1x_CmaPXHxxnFiaRHAfxGm94cm9xfz8apzc16iPNm3-PEXuf1bn_t4d6cu4RbDj',
    weather: 'Rainy',
    moods: ['Peaceful', 'Inspired'],
    category: 'Sunset',
    companion: 'Friends',
    isFavorite: false,
    coordinates: { lat: 51.5074, lng: -0.1278, xPercent: 47, yPercent: 28 },
  },
  {
    id: 'mem-5',
    title: 'Whispers of the Coast',
    city: 'Positano',
    country: 'Italy',
    date: '2024-05-14',
    formattedDate: 'May 14, 2024',
    story: 'Sun-drenched coastal town nestled into steep cliffs. Pastel houses stacked like vibrant blocks overlooking clear Mediterranean turquoise water.',
    notes: 'Ferry ride back was pure golden hour magic.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC_plwht32TFDZUJRSnpCEmNeXQyfhaQqV9-58GKzzusTYTfhHWhggGvy4I4OInRot6nKh1JygxWIMqHertmsNeVRD1GN13h0UOpyZ_29JaE2B19556VmY_jTHsMQUrsM83KQsdss2ZxyjjlgYYHpupmHR6vpURDLCnrCJAdLoqswEGCrjHOFOG0x75YoRv3zoyawjT59Q0zjRc-a9bed9f6C5Dz0ovOVe2LFxEg7kjTLTi28L8HvKLUAjYbFY1lZ-FHkeTBr7O8KiP',
    weather: 'Sunny',
    moods: ['Happy', 'Grateful'],
    category: 'Travel',
    companion: 'Partner',
    isFavorite: true,
    coordinates: { lat: 40.6281, lng: 14.485, xPercent: 52, yPercent: 37 },
  },
  {
    id: 'mem-6',
    title: 'The Scent of Old Pages',
    city: 'Florence',
    country: 'Italy',
    date: '2024-06-02',
    formattedDate: 'June 2, 2024',
    story: 'A cozy corner café with steam rising from a latte, accompanied by an aged leather-bound book. The light filtered softly through window panes.',
    notes: 'Spent three uninterrupted hours reading.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBOxOaB0h31B6_TQdhhRBIL6eBBQiqhBkCA38FS53EQZKkFalLsmyPiwbrin3_gYOmEEwueQwaduHC_0vggZUzpPXXyAbcJVJm6C-7kL1npvGFBSI3tCYVYUH193oP3Ei7bl33HV6W-_Yv42eKsWzJ5x211iUhfB2dv7QdXmcF--ny-OseSEwW4rOizvNucwlICuVqo8Cyrv8j0K4pHa8xxsGFWxHY50MerDQOGub8rtB9VhtVyQI-jnXzqt-2U2WLM9ECToOdF3VcL',
    weather: 'Cloudy',
    moods: ['Relaxed', 'Peaceful'],
    category: 'Coffee',
    companion: 'Myself',
    isFavorite: false,
    coordinates: { lat: 43.7696, lng: 11.2558, xPercent: 51, yPercent: 35 },
  },
  {
    id: 'mem-7',
    title: 'Mountain Solitude',
    city: 'Lauterbrunnen',
    country: 'Switzerland',
    date: '2024-04-20',
    formattedDate: 'April 20, 2024',
    story: 'Majestic Alpine peaks illuminated by sunset gradients of purple, orange, and rose gold. A quiet glacial lake reflecting snow-capped summits.',
    notes: 'The air was so crisp it felt like breathing crystal.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD7T9a2pH6keaCoS7FQKpxHFcocMvA1dflPvT8ZbF3e7-dIsUb3ViRzpDEKlUdj-MH6C1OGQeRGB1VhGS2BonUfSi6zH3Q4sfBXx_aZN19KE5YIuyYs-KDZtSCoOG0HmJqHJ1Fn9uJB-O2KJvRDOUv0IzRAlgEQvPw0_uS9uQ38GESMwJZgg4ZI4dgQLW5sBuirB3_15T1klzH-jAg9AfXWy2ZmhzCxIBOHGD1UClagLKwFbzQZqXm6JxrlT8QYhKZhpx4mMVt-1loV',
    weather: 'Golden',
    moods: ['Inspired', 'Grateful'],
    category: 'Nature',
    companion: 'Myself',
    isFavorite: true,
    coordinates: { lat: 46.5935, lng: 7.9077, xPercent: 50, yPercent: 32 },
  },
  {
    id: 'mem-8',
    title: 'Laughter After Dark',
    city: 'Tuscany',
    country: 'Italy',
    date: '2024-07-12',
    formattedDate: 'July 12, 2024',
    story: 'Candlelit garden feast with dear friends under hanging fairy lights. Homemade pasta, regional wine, and stories that lasted until the crickets fell silent.',
    notes: 'We sang old acoustic songs until midnight.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCx-h_PCYOOQ0NDBXJwnVk9lcMIeHsP_Xj_792p5o4lJHhcxSAfiYaMZ2z3aJM8IbipbvSn7TMMySnJ9FWkJqZ7vYnMIKyGY1y1wqtLFIZntANXePQHYZuRsZHP9Bp1mvA__vXxlo7VQ0aRa8rcQaAkjmdinJTBttNBIiCqsXZ-MnBWUqhCrKVTKNNT7O_lfyD3zXE-HrZqDk72MeRLopr6IU5NwUbAZ5tHi75EYn7S2CezOg47b5NzIExHWW4XMgSvtG-6K0w_mLyH',
    weather: 'Night',
    moods: ['Happy', 'Loved'],
    category: 'Friends',
    companion: 'Friends',
    isFavorite: false,
    coordinates: { lat: 43.7711, lng: 11.2486, xPercent: 51, yPercent: 35 },
  },
  {
    id: 'mem-9',
    title: 'Quiet Bloom',
    city: 'Kyoto',
    country: 'Japan',
    date: '2024-04-05',
    formattedDate: 'April 5, 2024',
    story: 'A delicate cherry blossom petal floating in a hand-blown glass bowl of clear spring water. Zen simplicity capturing spring’s ephemeral beauty.',
    notes: 'Witnessed the morning garden rake ceremony at Ryoan-ji.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAfk2Jbcu5dOPqZBYjRFab5RJSMtIcEG6q50AKjwvxz4_Pu0xBNYuSZv6eq7s-wN0HXBh6Z4Hb5HPBT3Fv5FlM71Xkge-yNwJuY0VqvpA-dQwQ467zTNsCICK9VEjWLqtuMAgdAgJvZrnbQ6YKZ58XhU233jqXddeBF4WyxsmEhe-nBWuRyZ8z5JC73FgjGK4bG5Nrzjx5Entv4qYdr8zN7a-5rPI5W6_vZa6Vt9go5R912g1IJpKkc4lGN1pfe3MHO28N4YLFnLhrY',
    weather: 'Sunny',
    moods: ['Peaceful', 'Relaxed'],
    category: 'Nature',
    companion: 'Myself',
    isFavorite: false,
    coordinates: { lat: 35.0116, lng: 135.7681, xPercent: 82, yPercent: 42 },
  },
  {
    id: 'mem-10',
    title: 'The Endless Sea',
    city: 'Merzouga',
    country: 'Morocco',
    date: '2024-03-28',
    formattedDate: 'March 28, 2024',
    story: 'Standing atop Erg Chebbi sand dunes at twilight. As the sun set, the golden sands cooled into deep terracottas under a blanket of emerging desert stars.',
    notes: 'Listened to Gnawa drum rhythms by the campfire.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD_fdRZosc96dL1jyvBG6Pbk1buQ8c0e0pQN2sexiRkSsShJbhZZIuh2QaOdmAPdmSAcLmd58DWX6iZmRJ_R7ekUPFos4sX-TlDUAcCe0ZZ1dQTRckzgzEgTOgtUscBvtz2Q_MuT_1QHJo1Km_6ZRc_KVHjW-lomkAycrH3bfJowOue7v2k0ZTIPY3Xiu4ss5v3qZkkDPvaaNiDRfr7N6GXR01vJ06joarLbi2GG_ah47lWSMUK0M8OJfKgc9mS7U0jAZqD8zKbr-hZ',
    weather: 'Night',
    moods: ['Inspired', 'Peaceful'],
    category: 'Travel',
    companion: 'A Stranger',
    isFavorite: true,
    coordinates: { lat: 31.0802, lng: -4.0133, xPercent: 46, yPercent: 43 },
  },
  {
    id: 'mem-11',
    title: 'Colors of Summer',
    city: 'Provence',
    country: 'France',
    date: '2024-08-10',
    formattedDate: 'August 10, 2024',
    story: 'Fresh heirloom tomatoes, torn basil leaves, and cold-pressed olive oil on a rustic olive-wood platter. The taste of sunshine captured in a single plate.',
    notes: 'Bought from a local farmer who spoke no English but smiled widely.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAXmcwYrC48w8m_D9GMhzbCpRlhX4hLf9l2BqfZohaxWr8kTShMgzpqIP3EuvaNaHvzHg0pTLN29Q-1iGpatFuH7QvXI_0jt6U19eGoJzsyv47wTMzNXvtn7GfgxcG-bDmXmwgLnVvI0NCoeVtJ4_07Z15wog-KGRBaW8Q86HpcMzIXodlk3-1VOYp1mmOpN6p23uzR1yh-vXNkSW2X2AC65ug0uISwbrGR__Jg0kP3YThcppxdfgwXSpF5vrA_NZ3OQkfFv-BdFVp0',
    weather: 'Sunny',
    moods: ['Happy', 'Grateful'],
    category: 'Food',
    companion: 'Family',
    isFavorite: false,
    coordinates: { lat: 43.9352, lng: 5.0674, xPercent: 49, yPercent: 34 },
  },
  {
    id: 'mem-12',
    title: 'Green Sanctuary',
    city: 'Olympic Forest',
    country: 'United States',
    date: '2024-06-18',
    formattedDate: 'June 18, 2024',
    story: 'Sunbeams piercing through ancient mossy canopy over a crystal stream. Long exposure water falling softly over emerald rocks in total wilderness silence.',
    notes: 'No cell service for 3 days. Pure liberation.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB1ALR35i69i6TmtMqki4_1XtghI-l0PZnFxtwXRo7jvDtJVfaHm-I0wTILsODkD035MTPGLNHkYgIzNAxJjwr9Giz7k1fwNfGrZvfuwQhzFIN9_C6A5m0MkWqEsJrgiR7T3PLrHWTx3VkYj2k6inIAvHFkSm4t960DdYArepCeUBshRirYrfMtLdLmysiekNu1CsSD8TNdFmuVdsncbWPTvkG0O9rTc-GSY5ZucSPVf4DjdCbeWAxJBOtWycWkXKnk6NVX26uN4oTC',
    weather: 'Cloudy',
    moods: ['Peaceful', 'Relaxed'],
    category: 'Nature',
    companion: 'Myself',
    isFavorite: false,
    coordinates: { lat: 47.8021, lng: -123.6044, xPercent: 18, yPercent: 31 },
  },
];

export const INITIAL_PLACES: Place[] = [
  {
    id: 'place-japan',
    country: 'Japan',
    city: 'Kyoto',
    memoriesCount: 8,
    lastVisited: 'Tokyo / Kyoto',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuASSQFMCz1Mgew4lG95gSWq43QDGYrbf2ZfQPfp1AnyS3LnN0CQmyV71ZPwEN9ZYfix2dGEGLffgGa6Z2JSp8q6sGLgwBKLYQRKxflNtXMWIlijiY76-XZ75WV9aQjBO_jiEAjfLbzUhpmP1lED0mdpXN87KWpZRHQrUAChK14lQOa1srvgba2iCrp0yRoa696haLSdq8ZQ7biKQPsJAApOsBW21eyvM0wDJMNTqrBzI7wDGkpq3MvT12PfKnXFyzl8R3nKYJFjrtRj',
    coordinates: { lat: 35.0116, lng: 135.7681, xPercent: 82, yPercent: 42 },
  },
  {
    id: 'place-italy',
    country: 'Italy',
    city: 'Amalfi & Positano',
    memoriesCount: 12,
    lastVisited: 'Florence',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC_plwht32TFDZUJRSnpCEmNeXQyfhaQqV9-58GKzzusTYTfhHWhggGvy4I4OInRot6nKh1JygxWIMqHertmsNeVRD1GN13h0UOpyZ_29JaE2B19556VmY_jTHsMQUrsM83KQsdss2ZxyjjlgYYHpupmHR6vpURDLCnrCJAdLoqswEGCrjHOFOG0x75YoRv3zoyawjT59Q0zjRc-a9bed9f6C5Dz0ovOVe2LFxEg7kjTLTi28L8HvKLUAjYbFY1lZ-FHkeTBr7O8KiP',
    coordinates: { lat: 41.8719, lng: 12.5674, xPercent: 52, yPercent: 36 },
  },
  {
    id: 'place-france',
    country: 'France',
    city: 'Paris & Provence',
    memoriesCount: 7,
    lastVisited: 'Paris',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDtrSyeQM82yxFP4aW7KUGHKn8h9ujlcbi0ltsHQb4NRRx9TahbDCd8L-0DbWtQK_vXStXBg-CcZxevXwqwGgahbwDpNC8FZvMW9T5NEDU6afu1yqcaYJlQEDo1Iy2prNCwFGhQvfIfXJkxVNYcdoGcKu5LfbOp6gpVBwDffQ0D4ywRd73aXwZ4nEw4gO6e5sTq5Dm_KMZDrlicHK3MJJdv_eWeevxqPBwJ3yMvcdL_zM-y7RruYVQu9hCjXCiLTbRxn8MgvnL7dQqh',
    coordinates: { lat: 46.2276, lng: 2.2137, xPercent: 49, yPercent: 33 },
  },
  {
    id: 'place-uk',
    country: 'United Kingdom',
    city: 'London',
    memoriesCount: 5,
    lastVisited: 'London',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBObeK0pxiKnCciZ9akYrkEdyAY9gixku5u73bYRWPR-CDuvn9x1X9FYhyrlZvnMMoDMD-kAOnTB5HmLbhaHShHnAm_my_RAQT76gn3zCy5TYRKBYN7LBC8NJz017p84blcTAOyPAkuYi9jhkyFxOAnIxxJ4oamJZxlvrOaiImDW_-mLWYMo0jAJDxH6WDHT2NpVdQ2sj6iAfyNC1x_CmaPXHxxnFiaRHAfxGm94cm9xfz8apzc16iPNm3-PEXuf1bn_t4d6cu4RbDj',
    coordinates: { lat: 55.3781, lng: -3.436, xPercent: 47, yPercent: 27 },
  },
  {
    id: 'place-switzerland',
    country: 'Switzerland',
    city: 'Lauterbrunnen',
    memoriesCount: 4,
    lastVisited: 'Interlaken',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD7T9a2pH6keaCoS7FQKpxHFcocMvA1dflPvT8ZbF3e7-dIsUb3ViRzpDEKlUdj-MH6C1OGQeRGB1VhGS2BonUfSi6zH3Q4sfBXx_aZN19KE5YIuyYs-KDZtSCoOG0HmJqHJ1Fn9uJB-O2KJvRDOUv0IzRAlgEQvPw0_uS9uQ38GESMwJZgg4ZI4dgQLW5sBuirB3_15T1klzH-jAg9AfXWy2ZmhzCxIBOHGD1UClagLKwFbzQZqXm6JxrlT8QYhKZhpx4mMVt-1loV',
    coordinates: { lat: 46.8182, lng: 8.2275, xPercent: 50, yPercent: 32 },
  },
  {
    id: 'place-morocco',
    country: 'Morocco',
    city: 'Merzouga Desert',
    memoriesCount: 3,
    lastVisited: 'Marrakech',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD_fdRZosc96dL1jyvBG6Pbk1buQ8c0e0pQN2sexiRkSsShJbhZZIuh2QaOdmAPdmSAcLmd58DWX6iZmRJ_R7ekUPFos4sX-TlDUAcCe0ZZ1dQTRckzgzEgTOgtUscBvtz2Q_MuT_1QHJo1Km_6ZRc_KVHjW-lomkAycrH3bfJowOue7v2k0ZTIPY3Xiu4ss5v3qZkkDPvaaNiDRfr7N6GXR01vJ06joarLbi2GG_ah47lWSMUK0M8OJfKgc9mS7U0jAZqD8zKbr-hZ',
    coordinates: { lat: 31.7917, lng: -7.0926, xPercent: 46, yPercent: 43 },
  },
  {
    id: 'place-dream-iceland',
    country: 'Iceland',
    city: 'Reykjavik & Southern Coast',
    memoriesCount: 0,
    lastVisited: 'Dreaming',
    imageUrl: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?q=80&w=1000&auto=format&fit=crop',
    isDreamDestination: true,
    coordinates: { lat: 64.9631, lng: -19.0208, xPercent: 42, yPercent: 20 },
  },
  {
    id: 'place-dream-peru',
    country: 'Peru',
    city: 'Cusco & Machu Picchu',
    memoriesCount: 0,
    lastVisited: 'Dreaming',
    imageUrl: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?q=80&w=1000&auto=format&fit=crop',
    isDreamDestination: true,
    coordinates: { lat: -9.19, lng: -75.0152, xPercent: 28, yPercent: 62 },
  }
];
